# coding: utf-8

"""
    Prison Guard Scheduling API

    This API manages the schedules of prison guards, ensuring a guard cannot be scheduled to be in two places at the same time. It supports querying schedules by guard ID and location name.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.schedule import Schedule  # noqa: E501
from swagger_client.rest import ApiException


class TestSchedule(unittest.TestCase):
    """Schedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedule(self):
        """Test Schedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.schedule.Schedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
