# coding: utf-8

"""
    Prison Guard Scheduling API

    This API manages the schedules of prison guards, ensuring a guard cannot be scheduled to be in two places at the same time. It supports querying schedules by guard ID and location name.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_schedules_get(self):
        """Test case for schedules_get

        Get a list of all schedules  # noqa: E501
        """
        pass

    def test_schedules_guard_guard_id_get(self):
        """Test case for schedules_guard_guard_id_get

        Get schedules by guard ID  # noqa: E501
        """
        pass

    def test_schedules_location_location_name_get(self):
        """Test case for schedules_location_location_name_get

        Get schedules by location name  # noqa: E501
        """
        pass

    def test_schedules_post(self):
        """Test case for schedules_post

        Create a new schedule  # noqa: E501
        """
        pass

    def test_schedules_schedule_id_delete(self):
        """Test case for schedules_schedule_id_delete

        Delete a schedule by ID  # noqa: E501
        """
        pass

    def test_schedules_schedule_id_get(self):
        """Test case for schedules_schedule_id_get

        Get a specific schedule by ID  # noqa: E501
        """
        pass

    def test_schedules_schedule_id_put(self):
        """Test case for schedules_schedule_id_put

        Update a schedule by ID  # noqa: E501
        """
        pass

    def test_schedules_switch_post(self):
        """Test case for schedules_switch_post

        Switch a schedule between two guards  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
