# coding: utf-8

"""
    Prison Guard Scheduling API

    This API manages the schedules of prison guards, ensuring a guard cannot be scheduled to be in two places at the same time. It supports querying schedules by guard ID and location name.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.schedules_switch_body import SchedulesSwitchBody  # noqa: E501
from swagger_client.rest import ApiException


class TestSchedulesSwitchBody(unittest.TestCase):
    """SchedulesSwitchBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedulesSwitchBody(self):
        """Test SchedulesSwitchBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.schedules_switch_body.SchedulesSwitchBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
