# coding: utf-8

# flake8: noqa

"""
    Prison Guard Scheduling API

    This API manages the schedules of prison guards, ensuring a guard cannot be scheduled to be in two places at the same time. It supports querying schedules by guard ID and location name.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.schedule import Schedule
from swagger_client.models.schedules_switch_body import SchedulesSwitchBody
